name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v1
      - name: Setup NodeJs 13.x
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
     - name: Commit and push if changed
        run: |-
          git add .
          git diff
          git config --global user.email hoxuanvinh1999@gmail.com
          git config --global user.name hoxuanvinh1999
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push 